### ISSUE TITLE
market 0.9.0 release

### ISSUE THREAD

**Issue by jnweiger** [owncloud/market#1351]
This is the server app release template, please copy the part below in a new ticket.
For instructions around app releases, see https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404326697/Releasing+Apps

### Reason

- Release needed for #1292 

### Product approval 

- [ ] ~Verify transifex commits (enterprise should update weekly, others daily): If folder `l10n` exists, then `git log` should show '[tx] updated from transifex` ...~
- [x] Check `info.xml` description and screenshot

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Create release branch with the format "release-$version"
- [x] Create "0.9.0 Testplan" --> #1350  ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core))
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404327434/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in https://github.com/owncloud/docs-server/issues/new .

### Marketing

- [ ] ~Update https://kiteworks.atlassian.net/wiki/spaces/PROD/pages/403801090/Upcoming+Releases~
- [ ] ~Check for any left over TODO's at https://kiteworks.monday.com/my_work (hide [x] done, empty)~

### Build

All actions to be done on the release branch (`git pull; git checkout -b release-x.x.x`) from here:
- [x] Bump version in `appinfo/info.xml` (no version suffix)
- [x] Check php version dependency and minimum ownCloud version dependency in `appinfo/info.xml`
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] `git tag -s v${version}-rc.1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}-rc.1` (see handbook for how to build)
- [x] Check buildlog for security reports
- [x] Check github security tab dependabot reports
    - [ ] -> if critical or high entries are reported: open a release blocker issue.
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [x] Watch out for untranslated strings when locale is de oder de_DE.
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (details https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404326697/Releasing+Apps)
- [x] Publish tarball for customers `github/owncloud/QA/tools/portal_upload_app.sh` - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (details https://kiteworks.atlassian.net/wiki/spaces/OG/pages/404326697/Releasing+Apps)
- [x] Send mail to release-coordination with link to this ticket and to the changelog `github/owncloud/QA/tools/release/oc_release.sh app:status`
- [ ] Copy email to rocket chat `#updates` channel (`remove all `https://` to avoid auto-expansions.)
- [x] Submit mail-text as a Markting Request via https://kiteworks.monday.com/boards/5983659465/views/130504071
	- DONE: Send Email to Alias: release-coordination@owncloud.com
	- DONE: Send Rocket Chat (internal)
	- DONE: Post to GitHub
	- DONE: Post to ownCloud Marketplace

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue
- [x] Check for any left over TODO's at https://kiteworks.monday.com/my_work (hide [x] done, empty)

**Comment by jnweiger** [comment]
Failed to build rc.1
> Downloading binary from https://github.com/sass/node-sass/releases/download/v9.0.0/linux-x64-83_binding.node
> Download complete

That file does not exist, it should not say 'Download complete'
```
Binary found at /var/www/owncloud/repo/market/node_modules/node-sass/vendor/linux-x64-83/binding.node
Testing binary
Binary has a problem: Error: /var/www/owncloud/repo/market/node_modules/node-sass/vendor/linux-x64-83/binding.node: file too short
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at module.exports (/var/www/owncloud/repo/market/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/var/www/owncloud/repo/market/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
Building the binary locally
Building: /usr/bin/node /var/www/owncloud/repo/market/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
...
```

After building from source, we have a binary that segfaults :-(

**Comment by jnweiger** [comment]
https://github.com/owncloud/market/releases/download/v0.9.0-rc.1/market-0.9.0-rc.1.tar.gz

**Comment by jnweiger** [comment]
## Issuses seen while testing
* [x] releasesigning:latest docker container needs an update
* [ ] https://github.com/owncloud/activity/issues/1211

**Comment by jnweiger** [comment]
QA passed.
