### ISSUE TITLE
stable10 build broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#186]
With node v8.5.0 and npm 5.3.0.

This is when building stable10 branch.

Here's the error:
```
touch node_modules/
/usr/bin/npm run build

> market@0.2.0 build /home/sign/administration-internal/release-scripts/temp-checkout302343/market
> webpack -p

Hash: ffd75a261d5bd9cda496
Version: webpack 2.7.0
Time: 297ms
                Asset     Size  Chunks             Chunk Names
./js/market.bundle.js  2.72 kB       0  [emitted]  main
   [0] ./src/default.js 1.96 kB {0} [built] [failed] [1 error]

ERROR in ./src/default.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/sign/administration-internal/release-scripts/temp-checkout302343/market"
    at /home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/sign/administration-internal/release-scripts/temp-checkout302343/market/node_modules/babel-loader/lib/index.js:163:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! market@0.2.0 build: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the market@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sign/.npm/_logs/2017-11-08T20_42_18_126Z-debug.log
make: *** [js/market.bundle.js] Error 2
Makefile:103: recipe for target 'js/market.bundle.js' failed
Error running make dist for market
```

Also reproducible locally on stable10.

master branch seems ok.

Please backport whatever changes. Or should we just merge the master branch into market's stable10 ? @DeepDiver1975 @felixheidecke @patrickjahns

**Comment by felixheidecke** [comment]
@PVince81 I suggest merging.

**Comment by PVince81** [comment]
Resolved by abandoning stable10 and making the release script pull the market app from the marketplace directly.

This also means we need to make a release there soon.
