### ISSUE TITLE
make dist fails on stable10

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#267]
Cannot build daily tarballs because of this error, which can be reproduced locally:

```
rm -f build/composer.phar
rm -Rf vendor/
rm -Rf node_modules/
rm -Rf build/dist
rm -Rf build
mkdir build
cd build && curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer (version 1.6.3) successfully installed to: /srv/www/htdocs/owncloud/apps3/market/build/composer.phar                                     
Use it: php composer.phar

php build/composer.phar install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
/usr/bin/npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

> node-sass@4.5.3 install /srv/www/htdocs/owncloud/apps3/market/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/vincent/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> node-sass@4.5.3 postinstall /srv/www/htdocs/owncloud/apps3/market/node_modules/node-sass
> node scripts/build.js

Binary found at /srv/www/htdocs/owncloud/apps3/market/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 833 packages in 56.872s
touch node_modules/
/usr/bin/npm run build

> market@0.2.0 build /srv/www/htdocs/owncloud/apps3/market
> webpack -p

Hash: 16185fe0088568e2c5a1
Version: webpack 2.7.0
Time: 540ms
                Asset     Size  Chunks             Chunk Names
./js/market.bundle.js  2.28 kB       0  [emitted]  main
   [0] ./src/default.js 1.52 kB {0} [built] [failed] [1 error]

ERROR in ./src/default.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/srv/www/htdocs/owncloud/apps3/market"
    at /srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/srv/www/htdocs/owncloud/apps3/market/node_modules/babel-loader/lib/index.js:163:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! market@0.2.0 build: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the market@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vincent/.npm/_logs/2018-02-27T10_11_04_649Z-debug.log
make: *** [Makefile:103: js/market.bundle.js] Error 2
```

@felixheidecke please have a look

Are we using lock files to prevent lib updates to break the build ?

**Comment by patrickjahns** [comment]
I've just tried and it works for me locally -whats your node / npm version? Whats running on the sign server?

**Comment by PVince81** [comment]
local node is v8.9.4 and sign server has v8.5.0

**Comment by patrickjahns** [comment]
I am testing with `owncloudci/php:latest` image now - will report back

**Comment by PVince81** [comment]
the problem disappeared I think
