### ISSUE TITLE
DB creation migration of apps randomly not running

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#48]
### Steps

1. Checkout core master
1. Delete "apps/customgroups" if any available
1. Setup OC from scratch
1. Clear cookies and cache in browser
1. Go to marketplace
1. Install "customgroups" app
1. Refresh the page

### Expected result
App enabled properly.

### Actual result
Internal server error.

```
{"reqId":"6OKjs4ULe7a6l47pujXB","level":3,"time":"2017-04-24T13:57:03+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"GET","url":"\/owncloud\/index.php\/apps\/market\/apps","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT m.`group_id`, m.`user_id`, m.`role`, g.`uri`, g.`display_name` FROM `oc_custom_group_member` m, `oc_custom_group` g WHERE (g.`group_id` = m.`group_id`) AND (`user_id` = ?) ORDER BY m.`group_id` ASC' with params [\\\"admin\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_custom_group_member' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT m.`group...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT m.`group...', Array, Array, NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT m.`group...', Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/customgroups\\\/lib\\\/CustomGroupsDatabaseHandler.php(128): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/customgroups\\\/lib\\\/CustomGroupsBackend.php(82): OCA\\\\CustomGroups\\\\CustomGroupsDatabaseHandler->getUserMemberships('admin', NULL)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Group\\\/Manager.php(300): OCA\\\\CustomGroups\\\\CustomGroupsBackend->getUserGroups('admin')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(249): OC\\\\Group\\\\Manager->getUserIdGroups('admin')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(909): OC_Util::setupFS()\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}"}
```

The DB creation migrations didn't run correctly.

Note that if you redo the same steps but **keep** the "customgroups" folder, then it will work fine.

Happens fairly consistently.

@SergioBertolinSG I remember you observed this once.

@DeepDiver1975

**Comment by PVince81** [comment]
going to debug this since everybody is busy already...

**Comment by PVince81** [comment]
This is what happens when I manually install customgroups from git:

```
0  OC\DB\MigrationService->createMigrationTable() /srv/www/htdocs/owncloud/lib/private/DB/MigrationService.php:104
1  OC\DB\MigrationService->getMigratedVersions() /srv/www/htdocs/owncloud/lib/private/DB/MigrationService.php:138
2  OC\DB\MigrationService->getMigrationsToExecute() /srv/www/htdocs/owncloud/lib/private/DB/MigrationService.php:199
3  OC\DB\MigrationService->migrate() /srv/www/htdocs/owncloud/lib/private/DB/MigrationService.php:344
4  OC\Installer::installShippedApp() /srv/www/htdocs/owncloud/lib/private/Installer.php:498
5  OC_App::enable() /srv/www/htdocs/owncloud/lib/private/legacy/app.php:363
6  OC\Core\Command\App\Enable->execute() /srv/www/htdocs/owncloud/core/Command/App/Enable.php:75
7  Symfony\Component\Console\Command\Command->run() /srv/www/htdocs/owncloud/lib/composer/symfony/console/Command/Command.php:262
8  Symfony\Component\Console\Application->doRunCommand() /srv/www/htdocs/owncloud/lib/composer/symfony/console/Application.php:826
9  Symfony\Component\Console\Application->doRun() /srv/www/htdocs/owncloud/lib/composer/symfony/console/Application.php:189
10 Symfony\Component\Console\Application->run() /srv/www/htdocs/owncloud/lib/composer/symfony/console/Application.php:120
11 OC\Console\Application->run() /srv/www/htdocs/owncloud/lib/private/Console/Application.php:160
12 require_once()  /srv/www/htdocs/owncloud/console.php:99
13 {main}          /srv/www/htdocs/owncloud/occ:11
```

In legacy/app.php: https://github.com/owncloud/core/blob/master/lib/private/legacy/app.php#L362

Basically `Installer::isInstalled('customgroups')` is false, so it called `Installer::installShippedApp('customgroup')` even though it's not a shipped app.

Well, the code is there, so it believes it's a shipped app... weird shit.

And as a side effect, it executes the migrations, so it's pure luck here.

Now when the market app installs an app, `Installer::isInstalled()` will return `false` so it doesn't go there. This means we'll need to implicitly trigger the migrations... somehow... Maybe run `updateApp($appId)` ?

**Comment by PVince81** [comment]
It also would not run "appinfo/install.php". It's not only about migrations but the whole logic inside `Installer::installShippedApp()`

As a quick workaround we could just call it from the market ?

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/27733
