### ISSUE TITLE
Missing image breaks ownCloud

### ISSUE THREAD

**Issue by PVince81** [owncloud/market#6]
It still sucks that core fails when an image is missing (other issue...)

Here with the market:

1. git clone master
1. git clone market into "apps" folder
1. setup OC
1. Login as admin

Getting this:
```
{"reqId":"4a+Atud5UNNMTXyuZNu6","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:market.svg webroot:\\\/owncloud serverroot:\\\/srv\\\/www\\\/htdocs\\\/owncloud\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/market\\\/lib\\\/Application.php(49): OC\\\\URLGenerator->imagePath('market', 'market.svg')\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/NavigationManager.php(63): OCA\\\\Market\\\\Application->OCA\\\\Market\\\\{closure}()\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(713): OC\\\\NavigationManager->getAll()\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(83): OC_App::getNavigation()\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(225): OC\\\\TemplateLayout->__construct('user', 'settings')\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(131): OC_Template->fetchPage()\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/settings\\\/admin.php(263): OC\\\\Template\\\\Base->printPage()\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(154) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#8 [internal function]: __lambda_func(Array)\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func('\\\\x00lambda_1291', Array)\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(894): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(46): OC::handleRequest()\\n
#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php\",\"Line\":201}","level":3,"time":"2016-11-14T16:31:26+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"admin"}
{"reqId":"lwzaghmUlKY3y0WpwK7i","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(146): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(202): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":211,\"User\":\"admin\"}","level":0,"time":"2016-11-14T16:31:27+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav","user":"admin"}
```

and OC is not usable as the web page doesn't open.

php5-5.6.27-355.1.x86_64
apache2-2.4.16-15.1.x86_64

@DeepDiver1975

**Comment by PVince81** [comment]
Hmm, there is no image at all in the repo. Did you forget checking it in ?
